version: "3.2"

services:
  webserver:
    build:
      context: ./images/webserver
    image: webdev-webserver:latest
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: $HOME/www/
        target: /var/www/
    networks:
      - backend

  mysql5:
    build:
      context: ./images/mysql5
    image: webdev-mysql5:latest
    container_name: mysql5
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - type: tmpfs
        source: sock
        target: /var/run/sock/
        volume:
          nocopy: true
      - type: volume
        source: mysql5
        target: /var/lib/mysql/
        volume:
          nocopy: true

  phpmyadmin:
    build:
      context: ./images/phpmyadmin
    image: webdev-phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ABSOLUTE_URI=http://phpmyadmin.local/
    volumes:
      - type: tmpfs
        source: sock
        target: /var/run/sock/
        volume:
          nocopy: true
    networks:
      - backend

  mailcatcher:
    build:
      context: ./images/mailcatcher
    image: webdev-mailcatcher:latest
    container_name: mailcatcher
    networks:
      - backend

  memcached:
    build:
      context: ./images/memcached
    image: webdev-memcached:latest
    container_name: memcached
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  sock:
  mysql5:
