version: "3.2"

services:
  sshd:
    build:
      context: ./images/sshd
      args:
        - GIT_USER_NAME=${DOCKER_DEV_GIT_USER}
        - GIT_USER_EMAIL=${DOCKER_DEV_GIT_EMAIL}
        - GIT_EDITOR=vim
    image: webdev-sshd:latest
    container_name: sshd
    ports:
      - "22:22"
    volumes:
      - type: bind
        source: $HOME/.ssh/
        target: /home/www-data/.ssh/
        volume:
          nocopy: true
      - type: bind
        source: $HOME/share/
        target: /home/www-data/share/
        volume:
          nocopy: true
      - type: volume
        source: www
        target: /var/www/
    networks:
      - backend

  nginx:
    build:
      context: ./images/nginx
    image: webdev-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: www
        target: /var/www/
    networks:
      backend:
        aliases:
          - dev.local
          - dev56.local
          - dev71.local

  php56:
    build:
      context: ./images/php56
    image: webdev-php56:latest
    container_name: php56
    volumes:
      - type: volume
        source: www
        target: /var/www/
    networks:
      - backend

  php71:
    build:
      context: ./images/php71
    image: webdev-php71:latest
    container_name: php71
    volumes:
      - type: volume
        source: www
        target: /var/www/
    networks:
      - backend

  mysql5:
    build:
      context: ./images/mysql5
    image: webdev-mysql5:latest
    container_name: mysql5
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - type: volume
        source: mysql5
        target: /var/lib/mysql/
    networks:
      - backend

  phpmyadmin:
    build:
      context: ./images/phpmyadmin
    image: webdev-phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ABSOLUTE_URI=http://phpmyadmin.local/
    networks:
      - backend

  mailcatcher:
    build:
      context: ./images/mailcatcher
    image: webdev-mailcatcher:latest
    container_name: mailcatcher
    networks:
      - backend

  memcached:
    build:
      context: ./images/memcached
    image: webdev-memcached:latest
    container_name: memcached
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql5:
  www:
